apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sprout-clusters.projectclearwater.org
  namespace: clearwater
spec:
  group: projectclearwater.org
  names:
    kind: SproutCluster
    listKind: SproutClusterList
    plural: sprout-clusters
    singular: sprout-cluster
  scope: Namespaced
  version: v1
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: clearwater-sprout-cluster-operator
  namespace: clearwater
rules:
- apiGroups:
  - projectclearwater.org
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: default-account-clearwater-sprout-cluster-operator
  namespace: clearwater
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: clearwater-sprout-cluster-operator
  apiGroup: rbac.authorization.k8s.io
